### ISSUE TITLE
This package does not build with GHC 9.4.8.

### ISSUE THREAD

**Issue by kindaro** [pxqr/krpc#4]
## what I do

```
% git rev-parse @
5c54f6570a27e1509ddf048a91bd69c05052f2f1
% ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.4.8
% cabal build
Build profile: -w ghc-9.4.8 -O1
In order, the following will be built (use -v for more details):
 - krpc-0.6.1.0 (lib) (first run)
Preprocessing library for krpc-0.6.1.0..
Building library for krpc-0.6.1.0..
[2 of 4] Compiling Network.KRPC.Method ( src/Network/KRPC/Method.hs, /tmp/krpc/dist-newstyle/build/x86_64-linux/ghc-9.4.8/krpc-0.6.1.0/build/Network/KRPC/Method.o, /tmp/krpc/dist-newstyle/build/x86_64-linux/ghc-9.4.8/krpc-0.6.1.0/build/Network/KRPC/Method.dyn_o ) [Source file changed]

src/Network/KRPC/Method.hs:61:16: error:
    • Could not deduce (Typeable a0) arising from a use of ‘typeOf’
      from the context: (Typeable a, Typeable b)
        bound by the type signature for:
                   showsMethod :: forall a b.
                                  (Typeable a, Typeable b) =>
                                  Method a b -> ShowS
        at src/Network/KRPC/Method.hs:(50,1)-(51,34)
      The type variable ‘a0’ is ambiguous
    • In the expression: typeOf (impossible :: b)
      In an equation for ‘valuesTy’: valuesTy = typeOf (impossible :: b)
      In an equation for ‘showsMethod’:
          showsMethod (Method name)
            = showString (unpack name)
                <>
                  showString " :: "
                    <> shows paramsTy <> showString " -> " <> shows valuesTy
            where
                impossible = error "KRPC.showsMethod: impossible"
                paramsTy = typeOf (impossible :: a)
                valuesTy = typeOf (impossible :: b)
   |
61 |     valuesTy = typeOf (impossible :: b)
   |                ^^^^^^
Error: cabal: Failed to build krpc-0.6.1.0.
```

## what should happen

Running `cabal build` should build the package.

## discussion

There are the following issues to handle:

* The type signature of `showsMethod` needs to be normalized. I guess there is a GHC bug here. The form `showsMethod :: forall a b. (Typeable a, Typeable b)` has the same meaning and compiles.
* Some white space about `@` needs to be cut away, as in <https://github.com/pxqr/base32-bytestring/issues/6>.
* The rules for default signatures must have been less restrictive — with GHC 9.4 the default signature `default liftHandler :: m a -> m a` cannot work. See <https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/default_signatures.html> for details. An equivalent working signature is `default liftHandler :: forall a. (MonadKRPC h m, h ~ m) => h a -> m a`.
* The functions `bindSocket` and `isBound` have been removed from the package `network` at version 3. Adding a version bound like so: `network >= 2.3 && <= 3.0` — and running `cabal build --allow-newer=base` makes it work for now. I opened an issue <https://github.com/haskell/network/issues/578> to see if there is a better solution.

Here is a patch: <https://gist.github.com/kindaro/0955e1e5c101cb1341e4e45d6f43838d>.
